apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 10
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/gin-app: "true"
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: DATABASE_HOST
              value: db
            - name: POSTGRES_DB
              value: bank
            - name: POSTGRES_PASSWORD
              value: "123"
            - name: POSTGRES_USER
              value: drack
          image: postgres:14
          name: postgres-accounts-simplebank-prod
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
      restartPolicy: Always
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
status: {}
