apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  type: LoadBalancer
  ports:
    - name: "5432"
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
