version: "3"

services:
  app:
    container_name: gin-accounts-simplebank
    build:
      target: builder
      context: .
    command: air .
    ports:
      - 8080:8080
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=Host(`localhost`) && PathPrefix(`/api/accounts`)"
    volumes:
      - .:/go/src/app
    depends_on:
      - db
      - db_test
      - reverse-proxy
    networks:
      - gin-app

  db:
    build:
      context: .docker/postgres
      target: development
    container_name: postgres-accounts-simplebank
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    expose:
      - 5433
    ports:
      - 5433:5433
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    networks:
      - gin-app

  db_test:
    build:
      context: .docker/postgres
      target: test
    container_name: postgres-test-accounts-simplebank
    environment:
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASSWORD_TEST}
      - POSTGRES_DB=${DB_NAME_TEST}
      - DATABASE_HOST=${DB_HOST_TEST}
    ports:
      - 5432:5432
    volumes:
      - .docker/dbDataTest:/var/lib/postgresql/data
    networks:
      - gin-app

  reverse-proxy:
    image: traefik:v2.0
    container_name: traefik-accounts-simplebank
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gin-app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container_simplebank
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - gin-app
    restart: unless-stopped

networks:
  gin-app:
    driver: bridge
